
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

! DATASOURCE SETTINGS
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=0000

! MINIO SETTINGS
minio.url=http://localhost:9000
minio.access-key=admin
minio.secret-key=00000000
minio.bucket-name=cloud-storage

! REDIS SETTINGS
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=0000

! JPA SETTINGS
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

! LOGGING SETTINGS
logging.level.com.example.cloud_file_storage=debug
logging.level.org.hibernate.sql=debug

! COOKIE
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=false
server.servlet.session.cookie.path=/
server.servlet.session.cookie.max-age=1800

! MULTIPART
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100KB
spring.servlet.multipart.max-request-size=200KB

! JAEGER
otel.service.name=cloud_storage
otel.exporter.otlp.endpoint=http://localhost:4318
otel.traces.exporter=otlp
otel.logs.exporter=none
spring.web.resources.add-mappings=true
management.endpoints.web.exposure.include:health,info,prometheus
management.endpoint.prometheus.access=unrestricted
management.metrics.tags.application: cloud-file-storage
