! ENCODING SETTINGS
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

! DATASOURCE SETTINGS
spring.datasource.url=jdbc:postgresql://postgres:5432/postgres
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}

! MINIO SETTINGS
minio.url=http://minio:9000
minio.access-key=${MINIO_ROOT_USER}
minio.secret-key=${MINIO_ROOT_PASSWORD}
minio.bucket-name=cloud-storage

! REDIS SETTINGS
spring.data.redis.host=redis
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}

! JAEGER
otel.service.name=cloud_storage
otel.exporter.otlp.endpoint=http://jaeger:4318
otel.traces.exporter=otlp
otel.logs.exporter=none
spring.web.resources.add-mappings=true
management.endpoints.web.exposure.include:health,info,prometheus
management.endpoint.prometheus.access=unrestricted
management.metrics.tags.application: cloud-file-storage

! JPA SETTINGS
spring.jpa.show-sql=false

! LIQUIBASE SETTINGS
spring.liquibase.drop-first=false

! LOGGING SETTINGS
logging.level.com.example.cloud_file_storage=info
logging.level.org.hibernate.sql=off
logging.level.org.hibernate=warn

! PERFORMANCE
spring.jpa.properties.hibernate.jdbc.batch_size=25
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

! COOKIE
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=false
server.servlet.session.cookie.path=/
server.servlet.session.cookie.max-age=1800

! MULTIPART
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100KB
spring.servlet.multipart.max-request-size=200KB
