spring.application.name=cloud-file-storage
spring.profiles.active=prod

! JPA SETTINGS
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

! LIQUIBASE SETTINGS
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml

! LOGGING SETTINGS
logging.level.com.example.cloud_file_storage=info